/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Book;
import model.Book_Name_and_Path;
import model.Data;
import model.DataHandler;

/**
 *
 * @author Admin
 */
public class LibraryFrame extends javax.swing.JFrame {

    public DataHandler dataHandler;
    /**
     * Creates new form LibraryFrame
     */
    public LibraryFrame(DataHandler dataHandler) {
        this.dataHandler = dataHandler;
        
        initComponents();
        this.addWindowListener(new WindowAdapter(){
            @Override
            public void windowClosing(WindowEvent e) {
                int result = JOptionPane.showConfirmDialog(null, "Bạn có muốn lưu thay đổi trước khi dóng?", "Thoát ứng dụng", JOptionPane.YES_NO_CANCEL_OPTION);
                if (result == JOptionPane.YES_OPTION) {
                    save_Change_and_Exit(1);
                } else if (result == JOptionPane.NO_OPTION) {
                    save_Change_and_Exit(0);
                } else {
                    // Hủy bỏ việc thoát
                    //save_Change_and_Exit(0);
                }
            }
        });
        this.add_RecentList_to_table();
    }
    public void save_Change_and_Exit(int i){
        if(i == 1){
            this.dataHandler.Write_RecentBook_to_File();
        }
        this.close();
        
    }   
    public void open(){
        this.setVisible(true);
    }
    public void close(){
        this.setVisible(false);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        Header_Panel_Library = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        find_Book = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        Book_Panel = new javax.swing.JPanel();
        Recent_Book_Lib_Panel = new javax.swing.JPanel();
        name_Recent = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_RecentBook = new javax.swing.JTable();
        Lib_Panel = new javax.swing.JPanel();
        name_Library = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        table_LibraryBook = new javax.swing.JTable();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Header_Panel_Library.setBackground(new java.awt.Color(255, 204, 204));
        Header_Panel_Library.setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));

        jPanel4.setBackground(new java.awt.Color(255, 204, 204));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        find_Book.setIcon(new javax.swing.ImageIcon("D:\\A.Documents\\Code\\JAVA\\Project\\ProReader\\src\\main\\java\\sourceImage\\Double-J-Design-Origami-Colored-Pencil-Red-search.32.png")); // NOI18N

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(find_Book, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(find_Book, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        Header_Panel_Library.add(jPanel1, java.awt.BorderLayout.LINE_END);

        jPanel5.setBackground(new java.awt.Color(255, 204, 204));
        jPanel5.setForeground(new java.awt.Color(255, 204, 204));

        jPanel6.setBackground(new java.awt.Color(255, 204, 204));

        jLabel3.setFont(new java.awt.Font("Agency FB", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setIcon(new javax.swing.ImageIcon("D:\\A.Documents\\Code\\JAVA\\Project\\ProReader\\src\\main\\java\\sourceImage\\Custom-Icon-Design-Flatastic-5-Library-2.48.png")); // NOI18N
        jLabel3.setText("Library");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 682, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        Header_Panel_Library.add(jPanel5, java.awt.BorderLayout.CENTER);

        getContentPane().add(Header_Panel_Library, java.awt.BorderLayout.PAGE_START);

        Book_Panel.setLayout(new java.awt.GridLayout(1, 0));

        Recent_Book_Lib_Panel.setLayout(new java.awt.BorderLayout());

        name_Recent.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel4.setText("+) Recent Book:");

        javax.swing.GroupLayout name_RecentLayout = new javax.swing.GroupLayout(name_Recent);
        name_Recent.setLayout(name_RecentLayout);
        name_RecentLayout.setHorizontalGroup(
            name_RecentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(name_RecentLayout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 473, Short.MAX_VALUE))
        );
        name_RecentLayout.setVerticalGroup(
            name_RecentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
        );

        Recent_Book_Lib_Panel.add(name_Recent, java.awt.BorderLayout.PAGE_START);

        jPanel3.setLayout(new java.awt.BorderLayout());

        table_RecentBook.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "STT", "Name", "Link"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        table_RecentBook.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_RecentBookMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table_RecentBook);

        jPanel3.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        Recent_Book_Lib_Panel.add(jPanel3, java.awt.BorderLayout.CENTER);

        Book_Panel.add(Recent_Book_Lib_Panel);

        Lib_Panel.setLayout(new java.awt.BorderLayout());

        name_Library.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel5.setText("+) Library:");

        javax.swing.GroupLayout name_LibraryLayout = new javax.swing.GroupLayout(name_Library);
        name_Library.setLayout(name_LibraryLayout);
        name_LibraryLayout.setHorizontalGroup(
            name_LibraryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(name_LibraryLayout.createSequentialGroup()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 461, Short.MAX_VALUE))
        );
        name_LibraryLayout.setVerticalGroup(
            name_LibraryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
        );

        Lib_Panel.add(name_Library, java.awt.BorderLayout.PAGE_START);

        jPanel7.setLayout(new java.awt.BorderLayout());

        table_LibraryBook.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "STT", "Name", "Link"
            }
        ));
        table_LibraryBook.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_LibraryBookMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(table_LibraryBook);

        jPanel7.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        Lib_Panel.add(jPanel7, java.awt.BorderLayout.CENTER);

        Book_Panel.add(Lib_Panel);

        getContentPane().add(Book_Panel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void table_LibraryBookMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_LibraryBookMouseClicked
        // TODO add your handling code here:
        int row = this.table_LibraryBook.getSelectedRow();
        accessBook_in_Library(row);
    }//GEN-LAST:event_table_LibraryBookMouseClicked

    private void table_RecentBookMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_RecentBookMouseClicked
        // TODO add your handling code here:
        int row = this.table_RecentBook.getSelectedRow();
        accessBook_in_RecentBook(row);
    }//GEN-LAST:event_table_RecentBookMouseClicked
    
    /**
     * @param args the command line arguments
     */
    
// 1. Add Data vào trong LibraryList, RecentList.
    
    public void add_LibraryList_to_table(){
        DefaultTableModel model = (DefaultTableModel) this.table_LibraryBook.getModel();
        model.setRowCount(0);
        for(int i = 0 ;i < this.dataHandler.getLibraryList().size(); i++){
            model.addRow(new Object[]{i + "", this.dataHandler.getLibraryList().get(i).getBookName(), this.dataHandler.getLibraryList().get(i).getBookPath()});     
        }
    }
    public void add_RecentList_to_table(){
        DefaultTableModel model = (DefaultTableModel) this.table_RecentBook.getModel();
        model.setRowCount(0);
        for(int i = 0 ;i < this.dataHandler.getRecentList().size(); i++){
            model.addRow(new Object[]{i + "", this.dataHandler.getRecentList().get(i).getBookName(), this.dataHandler.getRecentList().get(i).getBookPath()});     
        }
    }
    
    
//2. Thao tác với bảng:
    
    // Truy cập vào 1 sách trong Bảng Library.
    private void accessBook_in_Library(int id){
        Book_Name_and_Path bsp = this.dataHandler.getLibraryList().get(id);
        
        
        Book b = this.dataHandler.check_ExistBook_in_RecentList(bsp.getBookName(), bsp.getBookPath());
        Data data = new Data(b);
        MainFrame mainFrame = new MainFrame(data, this);
        mainFrame.setVisible(true);
        mainFrame.loadListMark_to_Table();
        this.close();
    }
    
    // Truy cập vào 1 sách trong Recent List.
    private void accessBook_in_RecentBook(int id){
        Book bsp = this.dataHandler.getRecentList().get(id);
        
        
        Book b = this.dataHandler.check_ExistBook_in_RecentList(bsp.getBookName(), bsp.getBookPath());
        Data data = new Data(b);
        MainFrame mainFrame = new MainFrame(data, this);
        mainFrame.setVisible(true);
        mainFrame.loadListMark_to_Table();
        this.close();
    }
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Book_Panel;
    private javax.swing.JPanel Header_Panel_Library;
    private javax.swing.JPanel Lib_Panel;
    private javax.swing.JPanel Recent_Book_Lib_Panel;
    private javax.swing.JLabel find_Book;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JPanel name_Library;
    private javax.swing.JPanel name_Recent;
    private javax.swing.JTable table_LibraryBook;
    private javax.swing.JTable table_RecentBook;
    // End of variables declaration//GEN-END:variables
}
