/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import com.formdev.flatlaf.FlatDarkLaf;
import com.formdev.flatlaf.FlatLightLaf;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.table.DefaultTableModel;
import model.Data;
import org.apache.pdfbox.rendering.PDFRenderer;

/**
 *
 * @author Admin
 */
public class MainFrame extends javax.swing.JFrame {
    
    public Data data;
    public LibraryFrame libraryFrame;
    public MainFrame(Data data, LibraryFrame libraryFrame) {
        this.data = data;
        this.libraryFrame = libraryFrame;
        initComponents();
        initData();
        drawPage();
        this.loadListMark_to_Table();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Menu_Bar = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        exit_to_Library = new javax.swing.JLabel();
        nameApp = new javax.swing.JLabel();
        setTheme = new javax.swing.JLabel();
        I1 = new javax.swing.JLabel();
        find = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        ReadBook_Panel = new javax.swing.JPanel();
        BookMark_Panel = new javax.swing.JPanel();
        features_Panel = new javax.swing.JPanel();
        add_BookMark = new javax.swing.JLabel();
        delete_BookMark = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_ListMark = new javax.swing.JTable();
        readBook_Panel = new javax.swing.JPanel();
        up_downPage_Panel = new javax.swing.JPanel();
        downPage = new javax.swing.JButton();
        status_page = new javax.swing.JLabel();
        upPage = new javax.swing.JButton();
        page_Panel = new javax.swing.JPanel();
        page_1 = new javax.swing.JLabel();
        page_2 = new javax.swing.JLabel();

        Menu_Bar.setLayout(new java.awt.GridLayout(10, 1));

        jLabel1.setText("zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
        );

        Menu_Bar.add(jPanel2);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 110, Short.MAX_VALUE)
        );

        Menu_Bar.add(jPanel3);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 110, Short.MAX_VALUE)
        );

        Menu_Bar.add(jPanel4);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 110, Short.MAX_VALUE)
        );

        Menu_Bar.add(jPanel5);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 110, Short.MAX_VALUE)
        );

        Menu_Bar.add(jPanel6);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 110, Short.MAX_VALUE)
        );

        Menu_Bar.add(jPanel7);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 110, Short.MAX_VALUE)
        );

        Menu_Bar.add(jPanel8);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 110, Short.MAX_VALUE)
        );

        Menu_Bar.add(jPanel9);

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 110, Short.MAX_VALUE)
        );

        Menu_Bar.add(jPanel10);

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 110, Short.MAX_VALUE)
        );

        Menu_Bar.add(jPanel11);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));

        exit_to_Library.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Desktop\\ProReader\\src\\main\\java\\sourceImage\\Amitjakhu-Drip-Exit.48.png")); // NOI18N
        exit_to_Library.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exit_to_LibraryMouseClicked(evt);
            }
        });

        nameApp.setFont(new java.awt.Font("Agency FB", 1, 36)); // NOI18N
        nameApp.setForeground(new java.awt.Color(0, 0, 0));
        nameApp.setText("PRO - READER");

        setTheme.setIcon(new javax.swing.ImageIcon("D:\\A.Documents\\Code\\JAVA\\Project\\ProReader\\src\\main\\java\\sourceImage\\Ionic-Ionicons-Moon.48.png")); // NOI18N
        setTheme.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                setThemeMouseClicked(evt);
            }
        });

        I1.setFont(new java.awt.Font("Agency FB", 1, 48)); // NOI18N
        I1.setForeground(new java.awt.Color(0, 0, 0));
        I1.setText("I");

        find.setIcon(new javax.swing.ImageIcon("D:\\A.Documents\\Code\\JAVA\\Project\\ProReader\\src\\main\\java\\sourceImage\\Fa-Team-Fontawesome-FontAwesome-Magnifying-Glass.48.png")); // NOI18N

        jLabel6.setFont(new java.awt.Font("Agency FB", 1, 48)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 51, 51));
        jLabel6.setText("I");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(exit_to_Library, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(nameApp, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 558, Short.MAX_VALUE)
                .addComponent(setTheme, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(I1)
                .addGap(39, 39, 39)
                .addComponent(find, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jLabel6)
                .addGap(153, 153, 153))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(26, 26, 26)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(I1, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
                                .addComponent(setTheme, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(find, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(nameApp, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(exit_to_Library, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        ReadBook_Panel.setLayout(new java.awt.BorderLayout());

        add_BookMark.setIcon(new javax.swing.ImageIcon("D:\\A.Documents\\Code\\JAVA\\Project\\ProReader\\src\\main\\java\\sourceImage\\Pictogrammers-Material-Book-plus.32.png")); // NOI18N
        add_BookMark.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                add_BookMarkMouseClicked(evt);
            }
        });

        delete_BookMark.setIcon(new javax.swing.ImageIcon("D:\\A.Documents\\Code\\JAVA\\Project\\ProReader\\src\\main\\java\\sourceImage\\Pictogrammers-Material-Book-minus.32.png")); // NOI18N
        delete_BookMark.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                delete_BookMarkMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout features_PanelLayout = new javax.swing.GroupLayout(features_Panel);
        features_Panel.setLayout(features_PanelLayout);
        features_PanelLayout.setHorizontalGroup(
            features_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(features_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(add_BookMark, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(delete_BookMark, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(64, Short.MAX_VALUE))
        );
        features_PanelLayout.setVerticalGroup(
            features_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(features_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(features_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(add_BookMark, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                    .addComponent(delete_BookMark, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        table_ListMark.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "STT", "Page"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        table_ListMark.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_ListMarkMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table_ListMark);

        javax.swing.GroupLayout BookMark_PanelLayout = new javax.swing.GroupLayout(BookMark_Panel);
        BookMark_Panel.setLayout(BookMark_PanelLayout);
        BookMark_PanelLayout.setHorizontalGroup(
            BookMark_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(features_Panel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        BookMark_PanelLayout.setVerticalGroup(
            BookMark_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BookMark_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(features_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 513, Short.MAX_VALUE)
                .addContainerGap())
        );

        ReadBook_Panel.add(BookMark_Panel, java.awt.BorderLayout.LINE_START);

        readBook_Panel.setLayout(new java.awt.BorderLayout());

        downPage.setText("<");
        downPage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                downPageMouseClicked(evt);
            }
        });
        downPage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                downPageActionPerformed(evt);
            }
        });

        status_page.setText("jLabel1");

        upPage.setText(">");
        upPage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                upPageMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout up_downPage_PanelLayout = new javax.swing.GroupLayout(up_downPage_Panel);
        up_downPage_Panel.setLayout(up_downPage_PanelLayout);
        up_downPage_PanelLayout.setHorizontalGroup(
            up_downPage_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(up_downPage_PanelLayout.createSequentialGroup()
                .addComponent(downPage, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(status_page, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(upPage, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 855, Short.MAX_VALUE))
        );
        up_downPage_PanelLayout.setVerticalGroup(
            up_downPage_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(up_downPage_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(up_downPage_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(status_page, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(downPage, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addComponent(upPage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        readBook_Panel.add(up_downPage_Panel, java.awt.BorderLayout.PAGE_END);

        page_Panel.setBackground(new java.awt.Color(255, 255, 255));
        page_Panel.setLayout(new java.awt.GridLayout(1, 0));
        page_Panel.add(page_1);
        page_Panel.add(page_2);

        readBook_Panel.add(page_Panel, java.awt.BorderLayout.CENTER);

        ReadBook_Panel.add(readBook_Panel, java.awt.BorderLayout.CENTER);

        getContentPane().add(ReadBook_Panel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void downPageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_downPageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_downPageActionPerformed

    int checkLsF = 2;
    private void setThemeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_setThemeMouseClicked
        if(checkLsF == 1){
            setTheme();
            checkLsF = 2;
        }
        else {
            setTheme();
            checkLsF = 1;
        }
    }//GEN-LAST:event_setThemeMouseClicked

    private void add_BookMarkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_add_BookMarkMouseClicked
        addBookMark_to_List();
        loadListMark_to_Table();
    }//GEN-LAST:event_add_BookMarkMouseClicked

    private void delete_BookMarkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_delete_BookMarkMouseClicked
        int row = table_ListMark.getSelectedRow();
        delete_BookMark(row);
    }//GEN-LAST:event_delete_BookMarkMouseClicked

    private void table_ListMarkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_ListMarkMouseClicked
        int row = table_ListMark.getSelectedRow();
        accessPage(row);
    }//GEN-LAST:event_table_ListMarkMouseClicked

    private void downPageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_downPageMouseClicked
        DownPage();
    }//GEN-LAST:event_downPageMouseClicked

    private void upPageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_upPageMouseClicked
        UpPage();
    }//GEN-LAST:event_upPageMouseClicked

    private void exit_to_LibraryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exit_to_LibraryMouseClicked
        int result = JOptionPane.showConfirmDialog(null, "Bạn có muốn lưu thay đổi trước khi thoát?", "Trở về Library?", JOptionPane.YES_NO_CANCEL_OPTION);
        if (result == JOptionPane.YES_OPTION) {
            // Lưu thay đổi
            save_Change(1);
        } else if (result == JOptionPane.NO_OPTION) {
            save_Change(0);
            //System.exit(0);
        } else {
            // Hủy bỏ việc thoát
            evt.consume();
        }
    }//GEN-LAST:event_exit_to_LibraryMouseClicked
    
    private void save_Change(int i){
        //1. Cập nhật vào recent List
        if(i == 1){
            this.libraryFrame.dataHandler.check_addNewBook_in_RecentList(this.data.book);
            this.libraryFrame.add_RecentList_to_table();
        }
        //2. Tắt MainFrame, bật Library_Frame.
        this.libraryFrame.open();
        this.setVisible(false);
    }
    
//1. Xử lý BookMark    

    //a. Thêm, Xóa Book Mark
    private void addBookMark_to_List(){
        this.data.book.listBookMark.add(((this.currentPage + 1) + ""));
        this.loadListMark_to_Table();
    }
    private void delete_BookMark(int idrow){
        int id_page = Integer.parseInt(this.data.book.listBookMark.get(idrow)) - 1;
        this.data.book.listBookMark.remove(idrow);
    }
    public void loadListMark_to_Table(){
        DefaultTableModel model = (DefaultTableModel) this.table_ListMark.getModel();
        model.setRowCount(0);
        for(int i = 0 ;i < this.data.book.listBookMark.size(); i++){
            model.addRow(new Object[]{i + "", this.data.book.listBookMark.get(i)});     
        }
    }
    
    //c. Truy cập vào 1 book Mark (event cho Table)
    private void accessPage(int id){
        this.currentPage = Integer.parseInt(this.data.book.listBookMark.get(id)) - 1;
       // System.out.println(this.currentPage);

        this.drawPage();
    }
    
    
    
//2. Dark/Light Mode.
    public void setTheme(){  
        try {
            if(this.checkLsF == 1){
                UIManager.setLookAndFeel(new FlatLightLaf());
            }
            else if(this.checkLsF == 2){
                UIManager.setLookAndFeel(new FlatDarkLaf());
            }
        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }   
        SwingUtilities.updateComponentTreeUI(this);
        this.pack();
        this.setSize(1220,730);
    }
    
    
    
    
// 3. Xử lý Menu Bar:
//    int w_MenuBar = 300;
//    int h_MenuBar = 637;
//    private void openMenuBar(){
//        System.out.println("opennn");
//        this.MenuBar.setSize(w_MenuBar, h_MenuBar);
//    }
//    private void closeMenuBar(){
//        System.out.println("close");
//        this.MenuBar.setSize(0, h_MenuBar);
//    }
//    
//    
    
    
 //4. Đọc Data:
    public int countPage;
    public int currentPage;
    public PDFRenderer render;
    public BufferedImage image1, image2;
    private void initData(){
        this.countPage = this.data.document.getNumberOfPages();
        this.currentPage = 0;
        this.render = new PDFRenderer(this.data.document);
    }
    
    public void drawPage(){
        status_page.setText((this.currentPage + 1) + ", " + (this.currentPage + 2) + " / " + this.countPage);
        try {
            this.image1 = render.renderImageWithDPI(this.currentPage,55);
            this.image2 = render.renderImageWithDPI(this.currentPage + 1, 55);
            //BufferedImage scaledImage1 = (BufferedImage) image1.getScaledInstance(480, 586, Image.SCALE_DEFAULT);
            //BufferedImage scaledImage2 = (BufferedImage) image2.getScaledInstance(480, 586, Image.SCALE_DEFAULT);
            ImageIcon imageIcon1 = new ImageIcon(image1);
            ImageIcon imageIcon2 = new ImageIcon(image2);
            
            ImageIcon imageIcon1_resize1 = new ImageIcon(imageIcon1.getImage().getScaledInstance(50, 50,1));
            ImageIcon imageIcon1_resize2= new ImageIcon(imageIcon2.getImage().getScaledInstance(50, 50,1));

            this.page_1.setIcon(new ImageIcon(image1));
            this.page_2.setIcon(new ImageIcon(image2));
        } catch (IOException ex) {
            ex.printStackTrace();
        }
    }
    
// 5. Chuyển trang:
    private void DownPage(){
        if(currentPage > 0){
            currentPage -= 2;
            drawPage();
        }
        
    }
    public void UpPage(){
        if(currentPage < countPage - 2){
            currentPage += 2;
            drawPage();
        }
    }
    
    
    
    
    
    
    
    
    
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BookMark_Panel;
    private javax.swing.JLabel I1;
    private javax.swing.JPanel Menu_Bar;
    private javax.swing.JPanel ReadBook_Panel;
    private javax.swing.JLabel add_BookMark;
    private javax.swing.JLabel delete_BookMark;
    private javax.swing.JButton downPage;
    private javax.swing.JLabel exit_to_Library;
    private javax.swing.JPanel features_Panel;
    private javax.swing.JLabel find;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel nameApp;
    private javax.swing.JLabel page_1;
    private javax.swing.JLabel page_2;
    private javax.swing.JPanel page_Panel;
    private javax.swing.JPanel readBook_Panel;
    private javax.swing.JLabel setTheme;
    private javax.swing.JLabel status_page;
    private javax.swing.JTable table_ListMark;
    private javax.swing.JButton upPage;
    private javax.swing.JPanel up_downPage_Panel;
    // End of variables declaration//GEN-END:variables
}
