/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import com.formdev.flatlaf.FlatDarkLaf;
import com.formdev.flatlaf.FlatLightLaf;
import java.awt.BorderLayout;
import java.awt.CardLayout;
import java.awt.FlowLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.awt.image.BufferedImage;
import java.io.BufferedInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.net.URL;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.table.DefaultTableModel;
import model.Book;
import model.Book_Name_and_Path;
import model.Data;
import model.DataHandler;
import org.apache.pdfbox.rendering.PDFRenderer;

/**
 *
 * @author Admin
 */
public class MainFrame extends javax.swing.JFrame {
    
    public DataHandler dataHandler;
    public CardLayout cardLayout;
    public Data data;
    public MainFrame(DataHandler dataHandler) {
        this.dataHandler = dataHandler;
        initComponents();
        this.cardLayout = (CardLayout) this.getContentPane().getLayout();
        this.cardLayout.next(this.getContentPane());
        this.setTheme();
        this.checkLsF = 2;
        this.addWindowListener(new WindowAdapter(){
            @Override
            public void windowClosing(WindowEvent e) {
                int result = JOptionPane.showConfirmDialog(null, "Bạn có muốn lưu thay đổi trước khi dóng?", "Thoát ứng dụng", JOptionPane.YES_NO_CANCEL_OPTION);
                if (result == JOptionPane.YES_OPTION) {
                    save_Change_and_Exit(1);
                } else if (result == JOptionPane.NO_OPTION) {
                    save_Change_and_Exit(0);
                } else {
                    // Hủy bỏ việc thoát
                    //e.consume();
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Menu_Bar = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        Panel_ReadingBook = new javax.swing.JPanel();
        HeaderPanel_inReadBook = new javax.swing.JPanel();
        exit_to_Library = new javax.swing.JLabel();
        nameApp = new javax.swing.JLabel();
        setTheme = new javax.swing.JLabel();
        I1 = new javax.swing.JLabel();
        instruction = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        ReadBook_Panel = new javax.swing.JPanel();
        BookMark_Panel = new javax.swing.JPanel();
        features_Panel = new javax.swing.JPanel();
        add_BookMark = new javax.swing.JLabel();
        delete_BookMark = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_ListMark = new javax.swing.JTable();
        readBook_Panel = new javax.swing.JPanel();
        up_downPage_Panel = new javax.swing.JPanel();
        button_updownPanel = new javax.swing.JPanel();
        downPage = new javax.swing.JButton();
        status_page = new javax.swing.JLabel();
        upPage = new javax.swing.JButton();
        jPanel14 = new javax.swing.JPanel();
        page_Panel = new javax.swing.JPanel();
        page_1 = new javax.swing.JLabel();
        page_2 = new javax.swing.JLabel();
        Library_Main_Panel = new javax.swing.JPanel();
        Header_Panel_Library = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        List_Book_Panel = new javax.swing.JPanel();
        Recent_Book_Lib_Panel = new javax.swing.JPanel();
        name_Recent = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel17 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        table_RecentBook = new javax.swing.JTable();
        Lib_Panel = new javax.swing.JPanel();
        name_Library = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        downLoad_From_Drive = new javax.swing.JLabel();
        open_In_This_PC = new javax.swing.JLabel();
        downLoad_from_Internet = new javax.swing.JLabel();
        jPanel18 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        table_LibraryBook = new javax.swing.JTable();

        Menu_Bar.setLayout(new java.awt.GridLayout(10, 1));

        jLabel1.setText("zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
        );

        Menu_Bar.add(jPanel2);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 110, Short.MAX_VALUE)
        );

        Menu_Bar.add(jPanel3);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 110, Short.MAX_VALUE)
        );

        Menu_Bar.add(jPanel4);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 110, Short.MAX_VALUE)
        );

        Menu_Bar.add(jPanel5);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 110, Short.MAX_VALUE)
        );

        Menu_Bar.add(jPanel6);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 110, Short.MAX_VALUE)
        );

        Menu_Bar.add(jPanel7);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 110, Short.MAX_VALUE)
        );

        Menu_Bar.add(jPanel8);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 110, Short.MAX_VALUE)
        );

        Menu_Bar.add(jPanel9);

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 110, Short.MAX_VALUE)
        );

        Menu_Bar.add(jPanel10);

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 110, Short.MAX_VALUE)
        );

        Menu_Bar.add(jPanel11);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        Panel_ReadingBook.setBackground(new java.awt.Color(255, 255, 204));
        Panel_ReadingBook.setLayout(new java.awt.BorderLayout());

        HeaderPanel_inReadBook.setBackground(new java.awt.Color(255, 255, 153));

        exit_to_Library.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exit_to_LibraryMouseClicked(evt);
            }
        });

        nameApp.setBackground(new java.awt.Color(255, 255, 204));
        nameApp.setFont(new java.awt.Font("Agency FB", 1, 36)); // NOI18N
        nameApp.setForeground(new java.awt.Color(0, 0, 0));
        nameApp.setText("PRO - READER");

        setTheme.setIcon(new javax.swing.ImageIcon("D:\\A.Documents\\Code\\JAVA\\Project\\ProReader\\src\\main\\java\\sourceImage\\Ionic-Ionicons-Moon.48.png")); // NOI18N
        setTheme.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                setThemeMouseClicked(evt);
            }
        });

        I1.setFont(new java.awt.Font("Agency FB", 1, 48)); // NOI18N
        I1.setForeground(new java.awt.Color(0, 0, 0));
        I1.setText("I");

        instruction.setIcon(new javax.swing.ImageIcon("D:\\A.Documents\\Code\\JAVA\\Project\\ProReader\\src\\main\\java\\sourceImage\\Fa-Team-Fontawesome-FontAwesome-Magnifying-Glass.48.png")); // NOI18N

        jLabel6.setFont(new java.awt.Font("Agency FB", 1, 48)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 51, 51));
        jLabel6.setText("I");

        javax.swing.GroupLayout HeaderPanel_inReadBookLayout = new javax.swing.GroupLayout(HeaderPanel_inReadBook);
        HeaderPanel_inReadBook.setLayout(HeaderPanel_inReadBookLayout);
        HeaderPanel_inReadBookLayout.setHorizontalGroup(
            HeaderPanel_inReadBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderPanel_inReadBookLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(exit_to_Library, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(nameApp, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 604, Short.MAX_VALUE)
                .addComponent(setTheme, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(I1)
                .addGap(39, 39, 39)
                .addComponent(instruction, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jLabel6)
                .addGap(153, 153, 153))
        );
        HeaderPanel_inReadBookLayout.setVerticalGroup(
            HeaderPanel_inReadBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderPanel_inReadBookLayout.createSequentialGroup()
                .addGroup(HeaderPanel_inReadBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(HeaderPanel_inReadBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(HeaderPanel_inReadBookLayout.createSequentialGroup()
                            .addGap(26, 26, 26)
                            .addGroup(HeaderPanel_inReadBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(I1, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
                                .addComponent(setTheme, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(instruction, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HeaderPanel_inReadBookLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(nameApp, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(HeaderPanel_inReadBookLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(exit_to_Library, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Panel_ReadingBook.add(HeaderPanel_inReadBook, java.awt.BorderLayout.PAGE_START);

        ReadBook_Panel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 0), 2));
        ReadBook_Panel.setLayout(new java.awt.BorderLayout());

        features_Panel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        add_BookMark.setIcon(new javax.swing.ImageIcon("D:\\A.Documents\\Code\\JAVA\\Project\\ProReader\\src\\main\\java\\sourceImage\\Pictogrammers-Material-Book-plus.32.png")); // NOI18N
        add_BookMark.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                add_BookMarkMouseClicked(evt);
            }
        });

        delete_BookMark.setIcon(new javax.swing.ImageIcon("D:\\A.Documents\\Code\\JAVA\\Project\\ProReader\\src\\main\\java\\sourceImage\\Pictogrammers-Material-Book-minus.32.png")); // NOI18N
        delete_BookMark.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                delete_BookMarkMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout features_PanelLayout = new javax.swing.GroupLayout(features_Panel);
        features_Panel.setLayout(features_PanelLayout);
        features_PanelLayout.setHorizontalGroup(
            features_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(features_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(add_BookMark, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(delete_BookMark, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(110, Short.MAX_VALUE))
        );
        features_PanelLayout.setVerticalGroup(
            features_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(features_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(features_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(add_BookMark, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                    .addComponent(delete_BookMark, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        table_ListMark.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        table_ListMark.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "STT", "Page", "Note"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        table_ListMark.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_ListMarkMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table_ListMark);

        javax.swing.GroupLayout BookMark_PanelLayout = new javax.swing.GroupLayout(BookMark_Panel);
        BookMark_Panel.setLayout(BookMark_PanelLayout);
        BookMark_PanelLayout.setHorizontalGroup(
            BookMark_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(features_Panel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        BookMark_PanelLayout.setVerticalGroup(
            BookMark_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BookMark_PanelLayout.createSequentialGroup()
                .addComponent(features_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 621, Short.MAX_VALUE))
        );

        ReadBook_Panel.add(BookMark_Panel, java.awt.BorderLayout.LINE_START);

        readBook_Panel.setLayout(new java.awt.BorderLayout());

        up_downPage_Panel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        up_downPage_Panel.setLayout(new java.awt.BorderLayout());

        button_updownPanel.setLayout(new java.awt.GridLayout(1, 0));

        downPage.setText("<");
        downPage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                downPageMouseClicked(evt);
            }
        });
        button_updownPanel.add(downPage);
        button_updownPanel.add(status_page);

        upPage.setText(">");
        upPage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                upPageMouseClicked(evt);
            }
        });
        button_updownPanel.add(upPage);

        up_downPage_Panel.add(button_updownPanel, java.awt.BorderLayout.LINE_START);

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 969, Short.MAX_VALUE)
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 31, Short.MAX_VALUE)
        );

        up_downPage_Panel.add(jPanel14, java.awt.BorderLayout.CENTER);

        readBook_Panel.add(up_downPage_Panel, java.awt.BorderLayout.PAGE_END);

        page_Panel.setBackground(new java.awt.Color(255, 255, 255));
        page_Panel.setLayout(new java.awt.GridLayout(1, 0));
        page_Panel.add(page_1);
        page_Panel.add(page_2);

        readBook_Panel.add(page_Panel, java.awt.BorderLayout.CENTER);

        ReadBook_Panel.add(readBook_Panel, java.awt.BorderLayout.CENTER);

        Panel_ReadingBook.add(ReadBook_Panel, java.awt.BorderLayout.CENTER);

        getContentPane().add(Panel_ReadingBook, "card2");

        Library_Main_Panel.setLayout(new java.awt.BorderLayout());

        Header_Panel_Library.setBackground(new java.awt.Color(255, 255, 153));
        Header_Panel_Library.setLayout(new java.awt.BorderLayout());

        jPanel13.setBackground(new java.awt.Color(255, 255, 153));

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 243, Short.MAX_VALUE)
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 112, Short.MAX_VALUE)
        );

        Header_Panel_Library.add(jPanel13, java.awt.BorderLayout.LINE_END);

        jPanel15.setBackground(new java.awt.Color(255, 255, 153));
        jPanel15.setForeground(new java.awt.Color(255, 204, 204));

        jPanel16.setBackground(new java.awt.Color(255, 255, 153));

        jLabel3.setFont(new java.awt.Font("Agency FB", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Library");

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel16Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 269, Short.MAX_VALUE))
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(682, Short.MAX_VALUE))
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        Header_Panel_Library.add(jPanel15, java.awt.BorderLayout.CENTER);

        Library_Main_Panel.add(Header_Panel_Library, java.awt.BorderLayout.PAGE_START);

        List_Book_Panel.setLayout(new java.awt.GridLayout(1, 0));

        Recent_Book_Lib_Panel.setLayout(new java.awt.BorderLayout());

        name_Recent.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel4.setText("+) Recent Book:");

        javax.swing.GroupLayout name_RecentLayout = new javax.swing.GroupLayout(name_Recent);
        name_Recent.setLayout(name_RecentLayout);
        name_RecentLayout.setHorizontalGroup(
            name_RecentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(name_RecentLayout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 473, Short.MAX_VALUE))
        );
        name_RecentLayout.setVerticalGroup(
            name_RecentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
        );

        Recent_Book_Lib_Panel.add(name_Recent, java.awt.BorderLayout.PAGE_START);

        jPanel17.setLayout(new java.awt.BorderLayout());

        table_RecentBook.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "STT", "Name", "Link"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        table_RecentBook.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_RecentBookMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(table_RecentBook);

        jPanel17.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        Recent_Book_Lib_Panel.add(jPanel17, java.awt.BorderLayout.CENTER);

        List_Book_Panel.add(Recent_Book_Lib_Panel);

        Lib_Panel.setLayout(new java.awt.BorderLayout());

        name_Library.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        name_Library.setLayout(new java.awt.BorderLayout());

        jLabel7.setText("+) Library:");
        name_Library.add(jLabel7, java.awt.BorderLayout.LINE_START);

        open_In_This_PC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                open_In_This_PCMouseClicked(evt);
            }
        });

        downLoad_from_Internet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                downLoad_from_InternetMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(417, Short.MAX_VALUE)
                .addComponent(downLoad_from_Internet, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(downLoad_From_Drive, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(open_In_This_PC, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(open_In_This_PC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(downLoad_from_Internet, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
            .addComponent(downLoad_From_Drive, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        name_Library.add(jPanel1, java.awt.BorderLayout.CENTER);

        Lib_Panel.add(name_Library, java.awt.BorderLayout.PAGE_START);

        jPanel18.setLayout(new java.awt.BorderLayout());

        table_LibraryBook.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "STT", "Name", "Link"
            }
        ));
        table_LibraryBook.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_LibraryBookMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(table_LibraryBook);

        jPanel18.add(jScrollPane3, java.awt.BorderLayout.CENTER);

        Lib_Panel.add(jPanel18, java.awt.BorderLayout.CENTER);

        List_Book_Panel.add(Lib_Panel);

        Library_Main_Panel.add(List_Book_Panel, java.awt.BorderLayout.CENTER);

        getContentPane().add(Library_Main_Panel, "card3");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    int checkLsF = 1;
    private void setThemeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_setThemeMouseClicked
        if(checkLsF == 1){
            setTheme();
            checkLsF = 2;
        }
        else {
            setTheme();
            checkLsF = 1;
        }
    }//GEN-LAST:event_setThemeMouseClicked

    private void add_BookMarkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_add_BookMarkMouseClicked
        addBookMark_to_List();
    }//GEN-LAST:event_add_BookMarkMouseClicked

    private void delete_BookMarkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_delete_BookMarkMouseClicked
        int row = table_ListMark.getSelectedRow();
        delete_BookMark(row);
        this.loadListMark_to_Table();
    }//GEN-LAST:event_delete_BookMarkMouseClicked

    private void table_ListMarkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_ListMarkMouseClicked
        int row = table_ListMark.getSelectedRow();
        accessPage(row);
    }//GEN-LAST:event_table_ListMarkMouseClicked

    private void exit_to_LibraryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exit_to_LibraryMouseClicked
        int result = JOptionPane.showConfirmDialog(null, "Bạn có muốn lưu thay đổi trước khi thoát?", "Back To Library?", JOptionPane.YES_NO_CANCEL_OPTION);
        if (result == JOptionPane.YES_OPTION) {
            // Lưu thay đổi
            save_Change(1);
        } else if (result == JOptionPane.NO_OPTION) {
            save_Change(0);
            //System.exit(0);
        } else {
            // Hủy bỏ việc thoát
            evt.consume();
        }
    }//GEN-LAST:event_exit_to_LibraryMouseClicked

    private void table_RecentBookMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_RecentBookMouseClicked
        // TODO add your handling code here:
        int row = this.table_RecentBook.getSelectedRow();
        accessBook_in_RecentBook(row);
    }//GEN-LAST:event_table_RecentBookMouseClicked

    private void table_LibraryBookMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_LibraryBookMouseClicked
        // TODO add your handling code here:
        int row = this.table_LibraryBook.getSelectedRow();
        accessBook_in_Library(row);
    }//GEN-LAST:event_table_LibraryBookMouseClicked

    private void downLoad_from_InternetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_downLoad_from_InternetMouseClicked
       // this.setText_Notify.setVisible(true);
        this.open_EnterText_Frame("Enter your URL here: ", "setURL");
    }//GEN-LAST:event_downLoad_from_InternetMouseClicked

    private void open_In_This_PCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_open_In_This_PCMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_open_In_This_PCMouseClicked

    private void upPageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_upPageMouseClicked
        // TODO add your handling code here:
        this.UpPage();
    }//GEN-LAST:event_upPageMouseClicked

    private void downPageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_downPageMouseClicked
        // TODO add your handling code here:
        this.DownPage();
    }//GEN-LAST:event_downPageMouseClicked
    
    private void save_Change(int i){
        //1. Cập nhật vào recent List
        if(i == 1){
            this.dataHandler.check_addNewBook_in_RecentList(this.data.book);
            this.add_RecentList_to_table();
        }
        //2. Tắt MainFrame, bật Library_Frame.
        this.cardLayout.next(this.getContentPane());
    }
    
    
//I. READING-BOOK-PANEL:

    
//1. Xử lý BookMark    
    //a. Thêm, Xóa Book Mark
    private void addBookMark_to_List(){
        this.data.book.listBookMark.add(((this.currentPage + 1) + ""));
        this.open_EnterText_Frame("Enter Note For Book Mark:", "setBookMark");
        
    }
    private void delete_BookMark(int idrow){
        int id_page = Integer.parseInt(this.data.book.listBookMark.get(idrow)) - 1;
        this.data.book.listBookMark.remove(idrow);
        
    }
    public void loadListMark_to_Table(){
        DefaultTableModel model = (DefaultTableModel) this.table_ListMark.getModel();
        model.setRowCount(0);
        for(int i = 0 ;i < this.data.book.listBookMark.size(); i++){
            model.addRow(new Object[]{i + "", this.data.book.listBookMark.get(i), this.data.book.listBookMark_Note.get(i)});     
        }
    }
    //c. Truy cập vào 1 book Mark (event cho Table)
    private void accessPage(int id){
        this.currentPage = Integer.parseInt(this.data.book.listBookMark.get(id)) - 1;
       // System.out.println(this.currentPage);
        this.drawPage();
    }
//2. Dark/Light Mode.
    public void setTheme(){  
        try {
            if(this.checkLsF == 1){
                UIManager.setLookAndFeel(new FlatLightLaf());
            }
            else if(this.checkLsF == 2){
                UIManager.setLookAndFeel(new FlatDarkLaf());
            }
        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }   
        SwingUtilities.updateComponentTreeUI(this);
        this.pack();
        this.setSize(1220,830);
    }
// 3. Xử lý Menu Bar:
//    int w_MenuBar = 300;
//    int h_MenuBar = 637;
//    private void openMenuBar(){
//        System.out.println("opennn");
//        this.MenuBar.setSize(w_MenuBar, h_MenuBar);
//    }
//    private void closeMenuBar(){
//        System.out.println("close");
//        this.MenuBar.setSize(0, h_MenuBar);
//    }
//    
//    
 //4. Đọc Data:
    public int countPage;
    public int currentPage;
    public PDFRenderer render;
    public BufferedImage image1, image2;
    private void initData(){
        this.countPage = this.data.document.getNumberOfPages();
        this.currentPage = 0;
        this.render = new PDFRenderer(this.data.document);
        this.add_RecentList_to_table();
    }
    
    public void drawPage(){
        status_page.setText((this.currentPage + 1) + ", " + (this.currentPage + 2) + " / " + this.countPage);
        try {
            this.image1 = render.renderImageWithDPI(this.currentPage,58);
            this.image2 = render.renderImageWithDPI(this.currentPage + 1, 58);
            //BufferedImage scaledImage1 = (BufferedImage) image1.getScaledInstance(480, 586, Image.SCALE_DEFAULT);
            //BufferedImage scaledImage2 = (BufferedImage) image2.getScaledInstance(480, 586, Image.SCALE_DEFAULT);
            ImageIcon imageIcon1 = new ImageIcon(image1);
            ImageIcon imageIcon2 = new ImageIcon(image2);
            
            ImageIcon imageIcon1_resize1 = new ImageIcon(imageIcon1.getImage().getScaledInstance(50, 50,1));
            ImageIcon imageIcon1_resize2= new ImageIcon(imageIcon2.getImage().getScaledInstance(50, 50,1));

            this.page_1.setIcon(new ImageIcon(image1));
            this.page_2.setIcon(new ImageIcon(image2));
        } catch (IOException ex) {
            ex.printStackTrace();
        }
    }
// 5. Chuyển trang:
    private void DownPage(){
        if(currentPage > 0){
            currentPage -= 2;
            drawPage();
        }
        
    }
    public void UpPage(){
        if(currentPage < countPage - 2){
            currentPage += 2;
            drawPage();
        }
    }
//6. Exit
    public void save_Change_and_Exit(int i){
        if(i == 1){
            this.dataHandler.Write_RecentBook_to_File();
        }
        this.setVisible(false);
    }       
   
    
// II. LIBRARY_PANEL:    

    
// 1. Add Data vào trong LibraryList, RecentList.
    
    public void add_LibraryList_to_table(){
        DefaultTableModel model = (DefaultTableModel) this.table_LibraryBook.getModel();
        model.setRowCount(0);
        for(int i = 0 ;i < this.dataHandler.getLibraryList().size(); i++){
            model.addRow(new Object[]{i + "", this.dataHandler.getLibraryList().get(i).getBookName(), this.dataHandler.getLibraryList().get(i).getBookPath()});     
        }
    }
    public void add_RecentList_to_table(){
        DefaultTableModel model = (DefaultTableModel) this.table_RecentBook.getModel();
        model.setRowCount(0);
        for(int i = 0 ;i < this.dataHandler.getRecentList().size(); i++){
            model.addRow(new Object[]{i + "", this.dataHandler.getRecentList().get(i).getBookName(), this.dataHandler.getRecentList().get(i).getBookPath()});     
        }
    }    
//2. Thao tác với bảng:
    
    // Truy cập vào 1 sách trong Bảng Library.
    private void accessBook_in_Library(int id){
        Book_Name_and_Path bsp = this.dataHandler.getLibraryList().get(id);
        
        
        Book b = this.dataHandler.check_ExistBook_in_RecentList(bsp.getBookName(), bsp.getBookPath());
        this.data = new Data(b);
        
        this.loadListMark_to_Table();
        this.cardLayout.next(this.getContentPane());
        this.initData();
        this.drawPage();
        this.loadListMark_to_Table();
    }
    
    // Truy cập vào 1 sách trong Recent List.
    private void accessBook_in_RecentBook(int id){
        Book bsp = this.dataHandler.getRecentList().get(id);
        Book b = this.dataHandler.check_ExistBook_in_RecentList(bsp.getBookName(), bsp.getBookPath());
        this.data = new Data(b);
        this.cardLayout.next(this.getContentPane());
        this.initData();
        this.drawPage();
        this.loadListMark_to_Table();
    }    

// 3. Thêm Sách bằng cách tải thông qua URL:
    
    //a. Cửa sổ nhập liệu:
    public void open_EnterText_Frame(String NamePanel, String type){
        SetText_Panel st = new SetText_Panel(this, NamePanel, type);
        st.setVisible(true);
    }
    //b: Lưu File.
    public void add_Book_to_Library_by_URL(String s){
        try {
            String address = s;
            URL url = new URL(address);
            String[] paths = address.split("/"); // Tách xâu, cái mk muốn lấy là tên của file để lưu vào Địa chỉ mình muốn.
            
            String name_Of_File = paths[paths.length - 1];
            
            
            InputStream is = url.openStream(); // để đọc file trên URl
            OutputStream os = new FileOutputStream("C:\\Users\\Admin\\Desktop\\ProReader\\src\\main\\java\\sourceFilePDF\\" + name_Of_File); // Lưu File xuống địa chỉ mình cần.
            byte[] bytes = new byte[1024];
            int len, downloaded = 0;
            
            while((len = is.read(bytes)) != -1){
                os.write(bytes, 0 ,len);
                downloaded += len;
                System.out.println("Downloaded... " + downloaded/1000.0f);
            }
            System.out.println("Download Completed");
            is.close();
            os.close();        

           
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BookMark_Panel;
    private javax.swing.JPanel HeaderPanel_inReadBook;
    private javax.swing.JPanel Header_Panel_Library;
    private javax.swing.JLabel I1;
    private javax.swing.JPanel Lib_Panel;
    private javax.swing.JPanel Library_Main_Panel;
    private javax.swing.JPanel List_Book_Panel;
    private javax.swing.JPanel Menu_Bar;
    private javax.swing.JPanel Panel_ReadingBook;
    private javax.swing.JPanel ReadBook_Panel;
    private javax.swing.JPanel Recent_Book_Lib_Panel;
    private javax.swing.JLabel add_BookMark;
    private javax.swing.JPanel button_updownPanel;
    private javax.swing.JLabel delete_BookMark;
    private javax.swing.JLabel downLoad_From_Drive;
    private javax.swing.JLabel downLoad_from_Internet;
    private javax.swing.JButton downPage;
    private javax.swing.JLabel exit_to_Library;
    private javax.swing.JPanel features_Panel;
    private javax.swing.JLabel instruction;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel nameApp;
    private javax.swing.JPanel name_Library;
    private javax.swing.JPanel name_Recent;
    private javax.swing.JLabel open_In_This_PC;
    private javax.swing.JLabel page_1;
    private javax.swing.JLabel page_2;
    private javax.swing.JPanel page_Panel;
    private javax.swing.JPanel readBook_Panel;
    private javax.swing.JLabel setTheme;
    private javax.swing.JLabel status_page;
    private javax.swing.JTable table_LibraryBook;
    private javax.swing.JTable table_ListMark;
    private javax.swing.JTable table_RecentBook;
    private javax.swing.JButton upPage;
    private javax.swing.JPanel up_downPage_Panel;
    // End of variables declaration//GEN-END:variables
}
